# Roles
ADMIN_ROLE_ID = 1
CLIENT_ROLE_ID = 2
PROVIDER_ROLE_ID = 3


# User status
USER_STATUS_ACTIVE = "activo"
USER_STATUS_INACTIVE = "inactivo"

ALLOWED_USER_STATUS = [
    USER_STATUS_ACTIVE,
    USER_STATUS_INACTIVE
]


# Email verification status
EMAIL_VERIFICATION_PENDING = "pendiente"
EMAIL_VERIFICATION_VERIFIED = "verificado"

ALLOWED_EMAIL_VERIFICATION_STATUS = [
    EMAIL_VERIFICATION_PENDING,
    EMAIL_VERIFICATION_VERIFIED
]


# Provider verification status
PROVIDER_STATUS_PENDING = "pendiente"
PROVIDER_STATUS_APPROVED = "aprobado"
PROVIDER_STATUS_REJECTED = "rechazado"

ALLOWED_PROVIDER_VERIFICATION_STATUS = [
    PROVIDER_STATUS_PENDING,
    PROVIDER_STATUS_APPROVED,
    PROVIDER_STATUS_REJECTED
]



# Product status
PRODUCT_STATUS_ACTIVE = "activo"
PRODUCT_STATUS_INACTIVE = "inactivo"

ALLOWED_PRODUCT_STATUS = [
    PRODUCT_STATUS_ACTIVE,
    PRODUCT_STATUS_INACTIVE
]


# Notification email status
EMAIL_STATUS_PENDING = "pendiente"
EMAIL_STATUS_SENT_SIMULATED = "enviado_simulado"
EMAIL_STATUS_FAILED = "fallido"

ALLOWED_NOTIFICATION_EMAIL_STATUS = [
    EMAIL_STATUS_PENDING,
    EMAIL_STATUS_SENT_SIMULATED,
    EMAIL_STATUS_FAILED
]


# Notification types
NOTIFICATION_TYPE_EMAIL_VERIFICATION = "verificacion_email"
NOTIFICATION_TYPE_RESERVATION_CONFIRMATION = "confirmacion_reserva"